spring:
  application:
    name: order-service
  cloud:
    loadbalancer:
      clients:
        payment-service:
          instances:
            - http://localhost:9002
  kafka:
    bootstrap-servers: localhost:29092
    auto-offset-reset: earliest
    consumer:
      group-id: my-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: quarkus-api
    password: quarkus-api
  jpa:
    hibernate:
      ddl-auto: 'update'
      show-sql: true
server:
  port: 9001

management:
  tracing:
    sampling:
      probability: 1.0  # 100% requests are traced
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    feign.Request: DEBUG
